### ISSUE TITLE
Make SteamBird production-ready

### ISSUE THREAD

**Issue by luuklsl** [StichtingIAPC/SteamBird#26]
Original issue by @rhbvkleef 
*******************************

Currently, SB has no way to enter production mode, or connect to a database other than SQLite. This is needed before being able to push to production. Some penetration testing also needs to be done.

**Comment by rhbvkleef** [comment]
SteamBird is not compatible with SQLite anymore. It is able to pull database credentials and driver type from environment (or local.py) and is therefore not really relevant anymore.
